name: Run Pipeline Daily

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
        # Run data pipeline
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
      - uses: opt-nc/setup-duckdb-action@v1.0.8
      - name: Run pipeline script
        env:
          APIKEY: ${{ secrets.LEGISCAN_APIKEY }}
        run: ./pipeline.bash
      - uses: stefanzweifel/git-auto-commit-action@v5
