name: Run Pipeline Daily

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        # Run data pipeline
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
      - uses: opt-nc/setup-duckdb-action@v1.0.8

      - name: Run pipeline script
        env:
          APIKEY: ${{ secrets.LEGISCAN_APIKEY }}
        run: ./pipeline.bash
      - name: Commit CSV updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated update"
          git push
